# This workflow will download a prebuilt Ruby version and install dependencies

name: Rails New

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Branch To Make Edits
      uses: actions/checkout@master
      with:
        ref: auto-rails-new

    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6

    - name: Install dependencies
      run: bundle init && bundle install rails && sudo apt-get install -y libsqlite3-dev

    - name: Create A New Branch
      uses: peterjgrainger/action-create-branch@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: auto-rails-new

    - name: Rails New
      run: rails new myapp --api

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.8.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Auto-generated `rails new <app> --api`
        author-email: hubot@github.com
        author-name: Hubot
        title: Scaffold Rails API App
        body: Auto-generated `rails new <app> --api`
        branch: auto-rails-new
        branch-suffix: none
