# This workflow will download a prebuilt Ruby version and install dependencies

name: Rails New

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install && apt-get install -y libsqlite3-dev
    - name: Rails New
      run: rails new myapp
